import test from "node:test";
import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import { PrismaClient, Prisma } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { withPrivacyDatabase } from "./database";
import { withActivityDatabase } from "../activity/database";
import { activityContext } from "../activity/context";
import { migratePersonalData, enforcePersonalData } from "../../../scripts/encrypt-personal-data";

const url = process.env.PII_TEST_DATABASE_URL;
process.env.PII_ENCRYPTION_KEYS = JSON.stringify({ test: randomBytes(32).toString("base64") });
process.env.PII_ACTIVE_KEY_ID = "test";
process.env.PII_INDEX_KEY = randomBytes(32).toString("base64");
process.env.PII_ALLOW_PLAINTEXT_READS = "false";

test("PII migration and application paths against a dedicated, disposable PostgreSQL database", { skip: !url }, async () => {
  if (!url!.includes("127.0.0.1:55439/pii_test")) throw new Error("Use the isolated pii_test database on port 55439.");
  const raw = new PrismaClient({ adapter: new PrismaPg({ connectionString: url!, options: "-c timezone=UTC" }) });
  const db = withActivityDatabase(withPrivacyDatabase(raw));
  const coachId = randomUUID();
  try {
    await raw.coach.create({ data: { id: coachId, sourceCoachId: "legacy-source", name: "가상 코치", normalizedName: "가상코치", accessToken: "legacy-token", privateProfile: { create: { phone: "010-0000-0000", birthDate: new Date("2000-01-02") } } } });
    const nullImport = await raw.dataImportRun.create({ data: { sourceType: "test", sourceName: "가상 원본", validationLogs: Prisma.JsonNull } });
    const dry = await migratePersonalData(raw, false);
    assert.ok(dry.coaches.plaintext > 0);
    assert.equal((await raw.coach.findUniqueOrThrow({ where: { id: coachId } })).name, "가상 코치");
    await assert.rejects(db.coach.findUniqueOrThrow({ where: { id: coachId } }));
    await migratePersonalData(raw, true);
    const migrated = await raw.coach.findUniqueOrThrow({ where: { id: coachId }, include: { privateProfile: true } });
    assert.match(migrated.name, /^pii:v1:/);
    assert.equal(migrated.privateProfile!.birthDate, null);
    const second = await migratePersonalData(raw, true);
    assert.equal(second.coaches.plaintext, 0);
    assert.equal((await raw.coach.findUniqueOrThrow({ where: { id: coachId } })).name, migrated.name);
    await enforcePersonalData(raw);
    assert.equal((await db.dataImportRun.findUniqueOrThrow({ where: { id: nullImport.id } })).validationLogs, null);
    await assert.rejects(raw.coach.update({ where: { id: coachId }, data: { name: "plaintext" } }));
    const actor = { requestId: randomUUID(), actorEmail: "user@example.test", actorName: "가상 사용자", actorType: "user" as const, route: "/api/coaches/[id]", method: "PATCH" };
    await activityContext.run(actor, () => db.coach.update({ where: { id: coachId }, data: { name: { set: "다른 코치" }, privateProfile: { update: { birthDate: new Date("2001-02-03"), email: "coach@example.test" } } } }));
    const found = await db.coach.findUniqueOrThrow({ where: { accessToken: "legacy-token" }, select: { name: true, privateProfile: { select: { birthDate: true, email: true } } } });
    assert.equal(found.name, "다른 코치");
    assert.equal(found.privateProfile!.birthDate!.toISOString().slice(0, 10), "2001-02-03");
    assert.equal(found.privateProfile!.email, "coach@example.test");
    assert.ok(!JSON.stringify(found).includes("PiiIndex"));
    assert.ok(!JSON.stringify(found).includes("Encrypted"));
    const log = await raw.activityChange.findFirstOrThrow({ where: { requestId: actor.requestId } });
    assert.match(log.actorEmail!, /^pii:v1:/);
    assert.ok(!JSON.stringify(log).includes("user@example.test"));
    assert.ok(!JSON.stringify(log).includes("다른 코치"));
    assert.equal((await db.activityChange.findFirstOrThrow({ where: { actorEmail: "user@example.test" } })).actorEmail, "user@example.test");
    await db.coach.create({ data: { sourceCoachId: "source-2", name: "가 코치", normalizedName: "가코치" } });
    await assert.rejects(db.coach.create({ data: { sourceCoachId: "source-2", name: "중복", normalizedName: "중복" } }));
    const search = await db.coach.findMany({ where: { name: { contains: "코치" } }, orderBy: { name: "asc" }, take: 1, select: { id: true } });
    assert.equal(search.length, 1);
    assert.deepEqual(Object.keys(search[0]), ["id"]);
    assert.equal((await db.coach.findUniqueOrThrow({ where: { id: search[0].id } })).name, "가 코치");
    await assert.rejects(db.$transaction(async tx => { await tx.coach.update({ where: { id: coachId }, data: { name: "취소" } }); throw new Error("rollback"); }));
    assert.equal((await db.coach.findUniqueOrThrow({ where: { id: coachId } })).name, "다른 코치");
    const announcement = await db.announcement.create({ data: { title: "가상 공지", content: "연락처 포함 본문", authorEmail: "author@example.test", attachments: { create: { fileName: "연락처.txt", mimeType: "text/plain", size: 5, data: Buffer.from("hello") } } }, include: { attachments: true } });
    assert.equal(Buffer.from(announcement.attachments[0].data).toString(), "hello");
    const stored = await raw.announcementAttachment.findFirstOrThrow({ where: { announcementId: announcement.id } });
    assert.ok(Buffer.from(stored.data).toString().startsWith("pii:v1:"));
    const imported = await db.dataImportRun.create({ data: { sourceType: "test", sourceName: "가상 파일", validationLogs: { email: "private@example.test" }, sourceRecords: { create: { sourceWorkbook: "private", sourceSheet: "sample", sourceRowNumber: 1, rowSnapshot: { phone: "010-0000-0000" } } } }, include: { sourceRecords: true } });
    assert.deepEqual(imported.validationLogs, { email: "private@example.test" });
    assert.ok(!JSON.stringify(await raw.dataImportRun.findUniqueOrThrow({ where: { id: imported.id }, include: { sourceRecords: true } })).includes("private@example.test"));
    await db.dataImportRun.update({ where: { id: imported.id }, data: { validationLogs: Prisma.JsonNull } });
    assert.equal((await db.dataImportRun.findUniqueOrThrow({ where: { id: imported.id } })).validationLogs, null);
    await db.member.upsert({ where: { role_sourceTeam_normalizedName: { role: "OM", sourceTeam: "TEAM_1", normalizedName: "가상멤버" } }, create: { role: "OM", sourceTeam: "TEAM_1", name: "가상 멤버", normalizedName: "가상멤버" }, update: { name: "가상 멤버 수정" } });
    const member = await db.member.upsert({ where: { role_sourceTeam_normalizedName: { role: "OM", sourceTeam: "TEAM_1", normalizedName: "가상멤버" } }, create: { role: "OM", sourceTeam: "TEAM_1", name: "새 멤버", normalizedName: "가상멤버" }, update: { name: "가상 멤버 수정" } });
    assert.equal(member.name, "가상 멤버 수정");
    const filtered = await db.coach.findMany({ where: { AND: [{ name: { contains: "코치" } }], name: { not: { equals: "가 코치" }, contains: "다른" } }, select: { name: true } });
    assert.deepEqual(filtered, [{ name: "다른 코치" }]);
    const omitted = await db.coachPrivateProfile.findUniqueOrThrow({ where: { coachId }, omit: { birthDate: true } });
    assert.ok(!("birthDate" in omitted));
    const sameContext = { ...actor, requestId: randomUUID() };
    await activityContext.run(sameContext, () => db.coach.update({ where: { id: coachId }, data: { name: "다른 코치" } }));
    assert.equal(await raw.activityChange.count({ where: { requestId: sameContext.requestId } }), 0);
    const privateLog = await raw.activityChange.findFirstOrThrow({ where: { requestId: actor.requestId, targetType: "coach_private_profiles" } });
    assert.ok(JSON.stringify(privateLog.changes).includes("birth_date"));
    await assert.rejects(db.coach.update({ where: { id: coachId }, data: { namePiiIndex: "f".repeat(64) } }));
    const token = await db.coach.findUniqueOrThrow({ where: { accessToken: "legacy-token" } });
    assert.equal(token.id, coachId);
  } finally { await raw.$disconnect(); }
});
