ALTER TABLE "coaches" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "coach_private_profiles" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "coach_schedules" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;
